---
name: rust
on: [push]  # yamllint disable-line rule:truthy
env:
  CARGO_TERM_COLOR: always
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v2
      - name: test
        run: cargo test
      - name: clippy
        run: cargo clippy
